/* empty css                      */import{a as f,S as L,i as s}from"./assets/vendor-COEJfE63.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function u(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const v="54673230-281fb694487da15dcd571070d",w="https://pixabay.com/api/";f.defaults.baseURL=w;async function m(n,o=1){return(await f.get("",{params:{key:v,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader-text"),S=new L(".gallery a",{captionsData:"alt",captionDelay:250});function y(n){const o=n.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p><b>Likes</b>${t.likes}</p>
          <p><b>Views</b>${t.views}</p>
          <p><b>Comments</b>${t.comments}</p>
          <p><b>Downloads</b>${t.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",o),S.refresh()}function q(){p.innerHTML=""}function g(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}const x=document.querySelector(".form"),i=document.querySelector(".load-more");let l="",a=1,d=0;x.addEventListener("submit",function(n){n.preventDefault();const o=n.currentTarget.elements["search-text"].value.trim();if(!o){s.warning({message:"Please enter a search query!",position:"bottomCenter"});return}l=o,a=1,q(),i.classList.add("hidden"),g(),m(l,a).then(function(t){if(d=t.totalHits,t.hits.length===0){s.info({message:"Sorry, I couldn't find this images.",position:"bottomCenter"});return}y(t.hits),d>15&&i.classList.remove("hidden")}).catch(function(){s.error({message:"Error fetching images.",position:"bottomCenter"})}).finally(function(){b()})});i.addEventListener("click",function(){a+=1,g(),i.classList.add("hidden"),m(l,a).then(function(n){y(n.hits),a*15>=d?s.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}):i.classList.remove("hidden")}).catch(function(){s.error({message:"I can't load more images.",position:"bottomCenter"})}).finally(function(){b()})});
//# sourceMappingURL=index.js.map
